//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class AuditedObjectWeakReference : XPLiteObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        Guid fGuidId;
        public Guid GuidId
        {
            get { return fGuidId; }
            set { SetPropertyValue<Guid>(nameof(GuidId), ref fGuidId, value); }
        }
        int fIntId;
        public int IntId
        {
            get { return fIntId; }
            set { SetPropertyValue<int>(nameof(IntId), ref fIntId, value); }
        }
        string fDisplayName;
        [Size(250)]
        public string DisplayName
        {
            get { return fDisplayName; }
            set { SetPropertyValue<string>(nameof(DisplayName), ref fDisplayName, value); }
        }
        [Association(@"AuditDataItemPersistentReferencesAuditedObjectWeakReference")]
        public XPCollection<AuditDataItemPersistent> AuditDataItemPersistents { get { return GetCollection<AuditDataItemPersistent>(nameof(AuditDataItemPersistents)); } }
    }

}
