//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class AuditDataItemPersistent : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fUserName;
        [Indexed(Name = @"iUserName_AuditDataItemPersistent")]
        public string UserName
        {
            get { return fUserName; }
            set { SetPropertyValue<string>(nameof(UserName), ref fUserName, value); }
        }
        DateTime fModifiedOn;
        [Indexed(Name = @"iModifiedOn_AuditDataItemPersistent")]
        public DateTime ModifiedOn
        {
            get { return fModifiedOn; }
            set { SetPropertyValue<DateTime>(nameof(ModifiedOn), ref fModifiedOn, value); }
        }
        string fOperationType;
        [Indexed(Name = @"iOperationType_AuditDataItemPersistent")]
        public string OperationType
        {
            get { return fOperationType; }
            set { SetPropertyValue<string>(nameof(OperationType), ref fOperationType, value); }
        }
        string fDescription;
        [Size(2048)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        AuditedObjectWeakReference fAuditedObject;
        [Association(@"AuditDataItemPersistentReferencesAuditedObjectWeakReference")]
        public AuditedObjectWeakReference AuditedObject
        {
            get { return fAuditedObject; }
            set { SetPropertyValue<AuditedObjectWeakReference>(nameof(AuditedObject), ref fAuditedObject, value); }
        }
        Guid fOldObject;
        [Indexed(Name = @"iOldObject_AuditDataItemPersistent")]
        public Guid OldObject
        {
            get { return fOldObject; }
            set { SetPropertyValue<Guid>(nameof(OldObject), ref fOldObject, value); }
        }
        Guid fNewObject;
        [Indexed(Name = @"iNewObject_AuditDataItemPersistent")]
        public Guid NewObject
        {
            get { return fNewObject; }
            set { SetPropertyValue<Guid>(nameof(NewObject), ref fNewObject, value); }
        }
        string fOldValue;
        [Size(1024)]
        public string OldValue
        {
            get { return fOldValue; }
            set { SetPropertyValue<string>(nameof(OldValue), ref fOldValue, value); }
        }
        string fNewValue;
        [Size(1024)]
        public string NewValue
        {
            get { return fNewValue; }
            set { SetPropertyValue<string>(nameof(NewValue), ref fNewValue, value); }
        }
        string fPropertyName;
        public string PropertyName
        {
            get { return fPropertyName; }
            set { SetPropertyValue<string>(nameof(PropertyName), ref fPropertyName, value); }
        }
    }

}
