//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class AustriaReturnCell : XPObject
    {
        string fTargetCell;
        public string TargetCell
        {
            get { return fTargetCell; }
            set { SetPropertyValue<string>(nameof(TargetCell), ref fTargetCell, value); }
        }
        EnumInstance fMaterialType;
        [Association(@"AustriaReturnCellReferencesEnumInstance2")]
        public EnumInstance MaterialType
        {
            get { return fMaterialType; }
            set { SetPropertyValue<EnumInstance>(nameof(MaterialType), ref fMaterialType, value); }
        }
        AustriaReturnLine fParentLine;
        [Association(@"AustriaReturnCellReferencesAustriaReturnLine")]
        public AustriaReturnLine ParentLine
        {
            get { return fParentLine; }
            set { SetPropertyValue<AustriaReturnLine>(nameof(ParentLine), ref fParentLine, value); }
        }
        EnumInstance fPackagingType;
        [Association(@"AustriaReturnCellReferencesEnumInstance3")]
        public EnumInstance PackagingType
        {
            get { return fPackagingType; }
            set { SetPropertyValue<EnumInstance>(nameof(PackagingType), ref fPackagingType, value); }
        }
        EnumInstance fDestination;
        [Association(@"AustriaReturnCellReferencesEnumInstance")]
        public EnumInstance Destination
        {
            get { return fDestination; }
            set { SetPropertyValue<EnumInstance>(nameof(Destination), ref fDestination, value); }
        }
        double fAllocation;
        public double Allocation
        {
            get { return fAllocation; }
            set { SetPropertyValue<double>(nameof(Allocation), ref fAllocation, value); }
        }
        int fCompRule;
        public int CompRule
        {
            get { return fCompRule; }
            set { SetPropertyValue<int>(nameof(CompRule), ref fCompRule, value); }
        }
        EnumInstance fSource;
        [Association(@"AustriaReturnCellReferencesEnumInstance4")]
        public EnumInstance Source
        {
            get { return fSource; }
            set { SetPropertyValue<EnumInstance>(nameof(Source), ref fSource, value); }
        }
        ComplianceRule fRule;
        [Association(@"AustriaReturnCellReferencesComplianceRule")]
        public ComplianceRule Rule
        {
            get { return fRule; }
            set { SetPropertyValue<ComplianceRule>(nameof(Rule), ref fRule, value); }
        }
        EnumInstance fMaterialCatery;
        [Persistent(@"MaterialCate ry")]
        [Association(@"AustriaReturnCellReferencesEnumInstance1")]
        public EnumInstance MaterialCatery
        {
            get { return fMaterialCatery; }
            set { SetPropertyValue<EnumInstance>(nameof(MaterialCatery), ref fMaterialCatery, value); }
        }
        int fMaterialCategory;
        public int MaterialCategory
        {
            get { return fMaterialCategory; }
            set { SetPropertyValue<int>(nameof(MaterialCategory), ref fMaterialCategory, value); }
        }
    }

}
