//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class BOM : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        Product fProduct;
        [Association(@"BOMReferencesProduct")]
        public Product Product
        {
            get { return fProduct; }
            set { SetPropertyValue<Product>(nameof(Product), ref fProduct, value); }
        }
        ProdWeight fProductWeight;
        [Association(@"BOMReferencesProdWeight")]
        public ProdWeight ProductWeight
        {
            get { return fProductWeight; }
            set { SetPropertyValue<ProdWeight>(nameof(ProductWeight), ref fProductWeight, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        DateTime fLastChangedOn;
        public DateTime LastChangedOn
        {
            get { return fLastChangedOn; }
            set { SetPropertyValue<DateTime>(nameof(LastChangedOn), ref fLastChangedOn, value); }
        }
        User fCreatedBy;
        [Association(@"BOMReferencesUser")]
        public User CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<User>(nameof(CreatedBy), ref fCreatedBy, value); }
        }
        User fLastChangedBy;
        [Association(@"BOMReferencesUser1")]
        public User LastChangedBy
        {
            get { return fLastChangedBy; }
            set { SetPropertyValue<User>(nameof(LastChangedBy), ref fLastChangedBy, value); }
        }
        Period fActiveFrom;
        [Association(@"BOMReferencesPeriod")]
        public Period ActiveFrom
        {
            get { return fActiveFrom; }
            set { SetPropertyValue<Period>(nameof(ActiveFrom), ref fActiveFrom, value); }
        }
        Period fActiveTo;
        [Association(@"BOMReferencesPeriod1")]
        public Period ActiveTo
        {
            get { return fActiveTo; }
            set { SetPropertyValue<Period>(nameof(ActiveTo), ref fActiveTo, value); }
        }
        Company fCompany;
        [Association(@"BOMReferencesCompany")]
        public Company Company
        {
            get { return fCompany; }
            set { SetPropertyValue<Company>(nameof(Company), ref fCompany, value); }
        }
        string fAssemblyCode;
        public string AssemblyCode
        {
            get { return fAssemblyCode; }
            set { SetPropertyValue<string>(nameof(AssemblyCode), ref fAssemblyCode, value); }
        }
        bool fIsAssembly;
        public bool IsAssembly
        {
            get { return fIsAssembly; }
            set { SetPropertyValue<bool>(nameof(IsAssembly), ref fIsAssembly, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        [Association(@"BOMItemReferencesBOM")]
        public XPCollection<BOMItem> BOMItems { get { return GetCollection<BOMItem>(nameof(BOMItems)); } }
        [Association(@"ProductReferencesBOM")]
        public XPCollection<Product> Products { get { return GetCollection<Product>(nameof(Products)); } }
        [Association(@"ProdWeightReferencesBOM")]
        public XPCollection<ProdWeight> ProdWeights { get { return GetCollection<ProdWeight>(nameof(ProdWeights)); } }
        [Association(@"SalesVolumeReferencesBOM")]
        public XPCollection<SalesVolume> SalesVolumes { get { return GetCollection<SalesVolume>(nameof(SalesVolumes)); } }
    }

}
