//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class Company : XPObject
    {
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        [Association(@"BOMReferencesCompany")]
        public XPCollection<BOM> BOMs { get { return GetCollection<BOM>(nameof(BOMs)); } }
        [Association(@"BOMItemReferencesCompany")]
        public XPCollection<BOMItem> BOMItems { get { return GetCollection<BOMItem>(nameof(BOMItems)); } }
        [Association(@"ComplianceRuleReferencesCompany")]
        public XPCollection<ComplianceRule> ComplianceRules { get { return GetCollection<ComplianceRule>(nameof(ComplianceRules)); } }
        [Association(@"CustomerReferencesCompany")]
        public XPCollection<Customer> Customers { get { return GetCollection<Customer>(nameof(Customers)); } }
        [Association(@"CustomerGroupReferencesCompany")]
        public XPCollection<CustomerGroup> CustomerGroups { get { return GetCollection<CustomerGroup>(nameof(CustomerGroups)); } }
        [Association(@"DimCustomerReferencesCompany")]
        public XPCollection<DimCustomer> DimCustomers { get { return GetCollection<DimCustomer>(nameof(DimCustomers)); } }
        [Association(@"DimItemTypeReferencesCompany")]
        public XPCollection<DimItemType> DimItemTypes { get { return GetCollection<DimItemType>(nameof(DimItemTypes)); } }
        [Association(@"DimMaterialReferencesCompany")]
        public XPCollection<DimMaterial> DimMaterials { get { return GetCollection<DimMaterial>(nameof(DimMaterials)); } }
        [Association(@"DimPartTypeReferencesCompany")]
        public XPCollection<DimPartType> DimPartTypes { get { return GetCollection<DimPartType>(nameof(DimPartTypes)); } }
        [Association(@"DimProductReferencesCompany")]
        public XPCollection<DimProduct> DimProducts { get { return GetCollection<DimProduct>(nameof(DimProducts)); } }
        [Association(@"EnumDomainReferencesCompany")]
        public XPCollection<EnumDomain> EnumDomains { get { return GetCollection<EnumDomain>(nameof(EnumDomains)); } }
        [Association(@"EnumDomainSubsetReferencesCompany")]
        public XPCollection<EnumDomainSubset> EnumDomainSubsets { get { return GetCollection<EnumDomainSubset>(nameof(EnumDomainSubsets)); } }
        [Association(@"EnumDomSubItemReferencesCompany")]
        public XPCollection<EnumDomSubItem> EnumDomSubItems { get { return GetCollection<EnumDomSubItem>(nameof(EnumDomSubItems)); } }
        [Association(@"EnumInstanceReferencesCompany")]
        public XPCollection<EnumInstance> EnumInstances { get { return GetCollection<EnumInstance>(nameof(EnumInstances)); } }
        [Association(@"FactPrimaryEndOfLifeReferencesCompany")]
        public XPCollection<FactPrimaryEndOfLife> FactPrimaryEndOfLives { get { return GetCollection<FactPrimaryEndOfLife>(nameof(FactPrimaryEndOfLives)); } }
        [Association(@"FactSUPItemsReferencesCompany")]
        public XPCollection<FactSUPItems> FactSUPItemsCollection { get { return GetCollection<FactSUPItems>(nameof(FactSUPItemsCollection)); } }
        [Association(@"MaterialMappingReferencesCompany")]
        public XPCollection<MaterialMapping> MaterialMappings { get { return GetCollection<MaterialMapping>(nameof(MaterialMappings)); } }
        [Association(@"PartReferencesCompany")]
        public XPCollection<Part> Parts { get { return GetCollection<Part>(nameof(Parts)); } }
        [Association(@"PartGroupReferencesCompany")]
        public XPCollection<PartGroup> PartGroups { get { return GetCollection<PartGroup>(nameof(PartGroups)); } }
        [Association(@"PeriodReferencesCompany")]
        public XPCollection<Period> Periods { get { return GetCollection<Period>(nameof(Periods)); } }
        [Association(@"ProductReferencesCompany")]
        public XPCollection<Product> Products { get { return GetCollection<Product>(nameof(Products)); } }
        [Association(@"ProductGroupReferencesCompany")]
        public XPCollection<ProductGroup> ProductGroups { get { return GetCollection<ProductGroup>(nameof(ProductGroups)); } }
        [Association(@"RepakReturnCellReferencesCompany")]
        public XPCollection<RepakReturnCell> RepakReturnCells { get { return GetCollection<RepakReturnCell>(nameof(RepakReturnCells)); } }
        [Association(@"RuleItemReferencesCompany")]
        public XPCollection<RuleItem> RuleItems { get { return GetCollection<RuleItem>(nameof(RuleItems)); } }
        [Association(@"SalesVolumeReferencesCompany")]
        public XPCollection<SalesVolume> SalesVolumes { get { return GetCollection<SalesVolume>(nameof(SalesVolumes)); } }
        [Association(@"SRAttributeReferencesCompany")]
        public XPCollection<SRAttribute> SRAttributes { get { return GetCollection<SRAttribute>(nameof(SRAttributes)); } }
        [Association(@"SupplierReferencesCompany")]
        public XPCollection<Supplier> Suppliers { get { return GetCollection<Supplier>(nameof(Suppliers)); } }
        [Association(@"SupplierGroupReferencesCompany")]
        public XPCollection<SupplierGroup> SupplierGroups { get { return GetCollection<SupplierGroup>(nameof(SupplierGroups)); } }
        [Association(@"TotalPackWeightReferencesCompany")]
        public XPCollection<TotalPackWeight> TotalPackWeights { get { return GetCollection<TotalPackWeight>(nameof(TotalPackWeights)); } }
        [Association(@"UKReturnCellReferencesCompany")]
        public XPCollection<UKReturnCell> UKReturnCells { get { return GetCollection<UKReturnCell>(nameof(UKReturnCells)); } }
    }

}
