//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class ComplexFileDefinition : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fTargetObjectType;
        public string TargetObjectType
        {
            get { return fTargetObjectType; }
            set { SetPropertyValue<string>(nameof(TargetObjectType), ref fTargetObjectType, value); }
        }
        int fImportMode;
        public int ImportMode
        {
            get { return fImportMode; }
            set { SetPropertyValue<int>(nameof(ImportMode), ref fImportMode, value); }
        }
        string fEmailTo;
        [Size(SizeAttribute.Unlimited)]
        public string EmailTo
        {
            get { return fEmailTo; }
            set { SetPropertyValue<string>(nameof(EmailTo), ref fEmailTo, value); }
        }
        ImportDefinitionCellMapping fEmailToMapping;
        [Association(@"ComplexFileDefinitionReferencesImportDefinitionCellMapping")]
        public ImportDefinitionCellMapping EmailToMapping
        {
            get { return fEmailToMapping; }
            set { SetPropertyValue<ImportDefinitionCellMapping>(nameof(EmailToMapping), ref fEmailToMapping, value); }
        }
        string fRecordPostprocessCodeMethod;
        [Size(254)]
        public string RecordPostprocessCodeMethod
        {
            get { return fRecordPostprocessCodeMethod; }
            set { SetPropertyValue<string>(nameof(RecordPostprocessCodeMethod), ref fRecordPostprocessCodeMethod, value); }
        }
        string fImportPostprocessCodeMethod;
        [Size(254)]
        public string ImportPostprocessCodeMethod
        {
            get { return fImportPostprocessCodeMethod; }
            set { SetPropertyValue<string>(nameof(ImportPostprocessCodeMethod), ref fImportPostprocessCodeMethod, value); }
        }
        string fIdentifyRecordBy;
        [Size(SizeAttribute.Unlimited)]
        public string IdentifyRecordBy
        {
            get { return fIdentifyRecordBy; }
            set { SetPropertyValue<string>(nameof(IdentifyRecordBy), ref fIdentifyRecordBy, value); }
        }
        [Association(@"ImportDefinitionColumnMappingReferencesComplexFileDefinition")]
        public XPCollection<ImportDefinitionColumnMapping> ImportDefinitionColumnMappings { get { return GetCollection<ImportDefinitionColumnMapping>(nameof(ImportDefinitionColumnMappings)); } }
    }

}
