//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using Microsoft.Extensions.Configuration;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{
    public static class ConnectionHelper
    {
        static Type[] persistentTypes = new Type[] {
            typeof(AuditDataItemPersistent),
            typeof(AuditedObjectWeakReference),
            typeof(AustriaReturn),
            typeof(AustriaReturnCell),
            typeof(AustriaReturnLine),
            typeof(BOM),
            typeof(BOMItem),
            typeof(CanadaReturn),
            typeof(CanadaReturnCell),
            typeof(CanadaReturnLine),
            typeof(Company),
            typeof(ComplexFileDefinition),
            typeof(ComplianceRule),
            typeof(Customer),
            typeof(CustomerAddress),
            typeof(CustomerCon),
            typeof(CustomerGroup),
            typeof(DimCustomer),
            typeof(Dimension),
            typeof(DimItemType),
            typeof(DimMaterial),
            typeof(DimPartType),
            typeof(DimProduct),
            typeof(EnumDomain),
            typeof(EnumDomainSubset),
            typeof(EnumDomSubItem),
            typeof(EnumInstance),
            typeof(FactPackagingSupplied),
            typeof(FactPrimaryEndOfLife),
            typeof(FactSUPItems),
            typeof(FileData),
            typeof(FileDataEx),
            typeof(FilteringCriterion),
            typeof(GRIPSObject),
            typeof(Group),
            typeof(IDASPackTotal),
            typeof(IDASReturn),
            typeof(IDASReturnCell),
            typeof(IDASReturnLine),
            typeof(ImportCrossReference),
            typeof(ImportCrossReferenceLine),
            typeof(ImportDefinition),
            typeof(ImportDefinitionCellMapping),
            typeof(ImportDefinitionColumnMapping),
            typeof(ImportDefinitionFolder),
            typeof(ImportLog),
            typeof(KPIDATA),
            typeof(KPIDEF),
            typeof(KPIMEMO),
            typeof(MaterialMapping),
            typeof(OpOperator),
            typeof(OpProperty),
            typeof(OpType),
            typeof(PackagingWeight),
            typeof(PackWeight),
            typeof(Part),
            typeof(PartGroup),
            typeof(Period),
            typeof(Privilege),
            typeof(Product),
            typeof(ProductGroup),
            typeof(ProdWeight),
            typeof(RepakReturn),
            typeof(RepakReturnCell),
            typeof(RepakReturnLine),
            typeof(RepakReturnLineFilter),
            typeof(RuleItem),
            typeof(SalesVolume),
            typeof(Sample),
            typeof(SampleCatery),
            typeof(SampleCategory),
            typeof(SampleCoefficient),
            typeof(SampleItem),
            typeof(SamplePackWeight),
            typeof(SRAttribute),
            typeof(Supplier),
            typeof(SupplierAddress),
            typeof(SupplierContact),
            typeof(SupplierGroup),
            typeof(TotalPackWeight),
            typeof(UKReturn),
            typeof(UKReturnCell),
            typeof(UKReturnLine),
            typeof(UpdateScriptResult),
            typeof(User),
            typeof(UserGroup),
            typeof(UserPrivilege)
        };
        public static Type[] GetPersistentTypes()
        {
            Type[] copy = new Type[persistentTypes.Length];
            Array.Copy(persistentTypes, copy, persistentTypes.Length);
            return copy;
        }
        public const string ConnectionStringName = "DESKTOP-T9GTKQLSQLEXPRESSCompany1";
        public static void Connect(IConfiguration configuration, DevExpress.Xpo.DB.AutoCreateOption autoCreateOption, bool threadSafe = false)
        {
            if (threadSafe)
            {
                var provider = GetConnectionProvider(configuration, autoCreateOption);
                var dictionary = new DevExpress.Xpo.Metadata.ReflectionDictionary();
                dictionary.GetDataStoreSchema(persistentTypes);
                XpoDefault.DataLayer = new ThreadSafeDataLayer(dictionary, provider);
            }
            else
            {
                XpoDefault.DataLayer = XpoDefault.GetDataLayer(configuration.GetConnectionString(ConnectionStringName), autoCreateOption);
            }
            XpoDefault.Session = null;
        }
        public static DevExpress.Xpo.DB.IDataStore GetConnectionProvider(IConfiguration configuration, DevExpress.Xpo.DB.AutoCreateOption autoCreateOption)
        {
            return XpoDefault.GetConnectionProvider(configuration.GetConnectionString(ConnectionStringName), autoCreateOption);
        }
        public static DevExpress.Xpo.DB.IDataStore GetConnectionProvider(IConfiguration configuration, DevExpress.Xpo.DB.AutoCreateOption autoCreateOption, out IDisposable[] objectsToDisposeOnDisconnect)
        {
            return XpoDefault.GetConnectionProvider(configuration.GetConnectionString(ConnectionStringName), autoCreateOption, out objectsToDisposeOnDisconnect);
        }
        public static IDataLayer GetDataLayer(IConfiguration configuration, DevExpress.Xpo.DB.AutoCreateOption autoCreateOption)
        {
            return XpoDefault.GetDataLayer(configuration.GetConnectionString(ConnectionStringName), autoCreateOption);
        }
    }

}
