//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class Dimension : XPObject
    {
        decimal fQuantity;
        public decimal Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<decimal>(nameof(Quantity), ref fQuantity, value); }
        }
        EnumInstance fUnitOfMeas;
        [Association(@"DimensionReferencesEnumInstance1")]
        public EnumInstance UnitOfMeas
        {
            get { return fUnitOfMeas; }
            set { SetPropertyValue<EnumInstance>(nameof(UnitOfMeas), ref fUnitOfMeas, value); }
        }
        EnumInstance fType;
        [Association(@"DimensionReferencesEnumInstance")]
        public EnumInstance Type
        {
            get { return fType; }
            set { SetPropertyValue<EnumInstance>(nameof(Type), ref fType, value); }
        }
        double fLength;
        public double Length
        {
            get { return fLength; }
            set { SetPropertyValue<double>(nameof(Length), ref fLength, value); }
        }
        double fWidth;
        public double Width
        {
            get { return fWidth; }
            set { SetPropertyValue<double>(nameof(Width), ref fWidth, value); }
        }
        double fHeight;
        public double Height
        {
            get { return fHeight; }
            set { SetPropertyValue<double>(nameof(Height), ref fHeight, value); }
        }
        Part fPart;
        [Association(@"DimensionReferencesPart")]
        public Part Part
        {
            get { return fPart; }
            set { SetPropertyValue<Part>(nameof(Part), ref fPart, value); }
        }
    }

}
