//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class DimProduct : XPObject
    {
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        DateTime fLastChangedOn;
        public DateTime LastChangedOn
        {
            get { return fLastChangedOn; }
            set { SetPropertyValue<DateTime>(nameof(LastChangedOn), ref fLastChangedOn, value); }
        }
        User fCreatedBy;
        [Association(@"DimProductReferencesUser")]
        public User CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<User>(nameof(CreatedBy), ref fCreatedBy, value); }
        }
        User fLastChangedBy;
        [Association(@"DimProductReferencesUser1")]
        public User LastChangedBy
        {
            get { return fLastChangedBy; }
            set { SetPropertyValue<User>(nameof(LastChangedBy), ref fLastChangedBy, value); }
        }
        Period fActiveFrom;
        [Association(@"DimProductReferencesPeriod")]
        public Period ActiveFrom
        {
            get { return fActiveFrom; }
            set { SetPropertyValue<Period>(nameof(ActiveFrom), ref fActiveFrom, value); }
        }
        Period fActiveTo;
        [Association(@"DimProductReferencesPeriod1")]
        public Period ActiveTo
        {
            get { return fActiveTo; }
            set { SetPropertyValue<Period>(nameof(ActiveTo), ref fActiveTo, value); }
        }
        Company fCompany;
        [Association(@"DimProductReferencesCompany")]
        public Company Company
        {
            get { return fCompany; }
            set { SetPropertyValue<Company>(nameof(Company), ref fCompany, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        int fSourceOid;
        public int SourceOid
        {
            get { return fSourceOid; }
            set { SetPropertyValue<int>(nameof(SourceOid), ref fSourceOid, value); }
        }
        int fSourceGroup;
        public int SourceGroup
        {
            get { return fSourceGroup; }
            set { SetPropertyValue<int>(nameof(SourceGroup), ref fSourceGroup, value); }
        }
        int fSourceSupplier;
        public int SourceSupplier
        {
            get { return fSourceSupplier; }
            set { SetPropertyValue<int>(nameof(SourceSupplier), ref fSourceSupplier, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fSupplierProdCode;
        public string SupplierProdCode
        {
            get { return fSupplierProdCode; }
            set { SetPropertyValue<string>(nameof(SupplierProdCode), ref fSupplierProdCode, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        string fEANCode;
        public string EANCode
        {
            get { return fEANCode; }
            set { SetPropertyValue<string>(nameof(EANCode), ref fEANCode, value); }
        }
        string fTUCCode;
        public string TUCCode
        {
            get { return fTUCCode; }
            set { SetPropertyValue<string>(nameof(TUCCode), ref fTUCCode, value); }
        }
        bool fIsActive;
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>(nameof(IsActive), ref fIsActive, value); }
        }
        bool fIsImport;
        public bool IsImport
        {
            get { return fIsImport; }
            set { SetPropertyValue<bool>(nameof(IsImport), ref fIsImport, value); }
        }
        string fPack;
        public string Pack
        {
            get { return fPack; }
            set { SetPropertyValue<string>(nameof(Pack), ref fPack, value); }
        }
        string fPackSize;
        public string PackSize
        {
            get { return fPackSize; }
            set { SetPropertyValue<string>(nameof(PackSize), ref fPackSize, value); }
        }
        string fGroupName;
        public string GroupName
        {
            get { return fGroupName; }
            set { SetPropertyValue<string>(nameof(GroupName), ref fGroupName, value); }
        }
        string fGroupCode;
        public string GroupCode
        {
            get { return fGroupCode; }
            set { SetPropertyValue<string>(nameof(GroupCode), ref fGroupCode, value); }
        }
        string fSupplierName;
        public string SupplierName
        {
            get { return fSupplierName; }
            set { SetPropertyValue<string>(nameof(SupplierName), ref fSupplierName, value); }
        }
        string fSupplierCode;
        public string SupplierCode
        {
            get { return fSupplierCode; }
            set { SetPropertyValue<string>(nameof(SupplierCode), ref fSupplierCode, value); }
        }
        string fBrand;
        public string Brand
        {
            get { return fBrand; }
            set { SetPropertyValue<string>(nameof(Brand), ref fBrand, value); }
        }
        int fSourceGroupParent;
        public int SourceGroupParent
        {
            get { return fSourceGroupParent; }
            set { SetPropertyValue<int>(nameof(SourceGroupParent), ref fSourceGroupParent, value); }
        }
        string fGroupParentName;
        public string GroupParentName
        {
            get { return fGroupParentName; }
            set { SetPropertyValue<string>(nameof(GroupParentName), ref fGroupParentName, value); }
        }
        string fGroupParentCode;
        public string GroupParentCode
        {
            get { return fGroupParentCode; }
            set { SetPropertyValue<string>(nameof(GroupParentCode), ref fGroupParentCode, value); }
        }
        string fGroup_Level_1;
        public string Group_Level_1
        {
            get { return fGroup_Level_1; }
            set { SetPropertyValue<string>(nameof(Group_Level_1), ref fGroup_Level_1, value); }
        }
        string fGroup_Level_2;
        public string Group_Level_2
        {
            get { return fGroup_Level_2; }
            set { SetPropertyValue<string>(nameof(Group_Level_2), ref fGroup_Level_2, value); }
        }
        string fGroup_Level_3;
        public string Group_Level_3
        {
            get { return fGroup_Level_3; }
            set { SetPropertyValue<string>(nameof(Group_Level_3), ref fGroup_Level_3, value); }
        }
        string fCatery_Name;
        [Persistent(@"Cate ry_Name")]
        public string Catery_Name
        {
            get { return fCatery_Name; }
            set { SetPropertyValue<string>(nameof(Catery_Name), ref fCatery_Name, value); }
        }
        string fPortfolio_Name;
        public string Portfolio_Name
        {
            get { return fPortfolio_Name; }
            set { SetPropertyValue<string>(nameof(Portfolio_Name), ref fPortfolio_Name, value); }
        }
        string fCategory_Name;
        public string Category_Name
        {
            get { return fCategory_Name; }
            set { SetPropertyValue<string>(nameof(Category_Name), ref fCategory_Name, value); }
        }
        [Association(@"FactPrimaryEndOfLifeReferencesDimProduct")]
        public XPCollection<FactPrimaryEndOfLife> FactPrimaryEndOfLives { get { return GetCollection<FactPrimaryEndOfLife>(nameof(FactPrimaryEndOfLives)); } }
        [Association(@"FactSUPItemsReferencesDimProduct")]
        public XPCollection<FactSUPItems> FactSUPItemsCollection { get { return GetCollection<FactSUPItems>(nameof(FactSUPItemsCollection)); } }
    }

}
