//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class EnumDomSubItem : XPObject
    {
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        DateTime fLastChangedOn;
        public DateTime LastChangedOn
        {
            get { return fLastChangedOn; }
            set { SetPropertyValue<DateTime>(nameof(LastChangedOn), ref fLastChangedOn, value); }
        }
        User fCreatedBy;
        [Association(@"EnumDomSubItemReferencesUser")]
        public User CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<User>(nameof(CreatedBy), ref fCreatedBy, value); }
        }
        User fLastChangedBy;
        [Association(@"EnumDomSubItemReferencesUser1")]
        public User LastChangedBy
        {
            get { return fLastChangedBy; }
            set { SetPropertyValue<User>(nameof(LastChangedBy), ref fLastChangedBy, value); }
        }
        Period fActiveFrom;
        [Association(@"EnumDomSubItemReferencesPeriod")]
        public Period ActiveFrom
        {
            get { return fActiveFrom; }
            set { SetPropertyValue<Period>(nameof(ActiveFrom), ref fActiveFrom, value); }
        }
        Period fActiveTo;
        [Association(@"EnumDomSubItemReferencesPeriod1")]
        public Period ActiveTo
        {
            get { return fActiveTo; }
            set { SetPropertyValue<Period>(nameof(ActiveTo), ref fActiveTo, value); }
        }
        Company fCompany;
        [Association(@"EnumDomSubItemReferencesCompany")]
        public Company Company
        {
            get { return fCompany; }
            set { SetPropertyValue<Company>(nameof(Company), ref fCompany, value); }
        }
        EnumDomainSubset fSubset;
        [Association(@"EnumDomSubItemReferencesEnumDomainSubset")]
        public EnumDomainSubset Subset
        {
            get { return fSubset; }
            set { SetPropertyValue<EnumDomainSubset>(nameof(Subset), ref fSubset, value); }
        }
        EnumDomain fDomain;
        [Association(@"EnumDomSubItemReferencesEnumDomain")]
        public EnumDomain Domain
        {
            get { return fDomain; }
            set { SetPropertyValue<EnumDomain>(nameof(Domain), ref fDomain, value); }
        }
        EnumInstance fInstance;
        [Association(@"EnumDomSubItemReferencesEnumInstance")]
        public EnumInstance Instance
        {
            get { return fInstance; }
            set { SetPropertyValue<EnumInstance>(nameof(Instance), ref fInstance, value); }
        }
    }

}
