//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class FactPackagingSupplied : XPObject
    {
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        DateTime fLastChangedOn;
        public DateTime LastChangedOn
        {
            get { return fLastChangedOn; }
            set { SetPropertyValue<DateTime>(nameof(LastChangedOn), ref fLastChangedOn, value); }
        }
        int fCreatedBy;
        public int CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<int>(nameof(CreatedBy), ref fCreatedBy, value); }
        }
        int fLastChangedBy;
        public int LastChangedBy
        {
            get { return fLastChangedBy; }
            set { SetPropertyValue<int>(nameof(LastChangedBy), ref fLastChangedBy, value); }
        }
        int fActiveFrom;
        public int ActiveFrom
        {
            get { return fActiveFrom; }
            set { SetPropertyValue<int>(nameof(ActiveFrom), ref fActiveFrom, value); }
        }
        int fActiveTo;
        public int ActiveTo
        {
            get { return fActiveTo; }
            set { SetPropertyValue<int>(nameof(ActiveTo), ref fActiveTo, value); }
        }
        int fCompany;
        public int Company
        {
            get { return fCompany; }
            set { SetPropertyValue<int>(nameof(Company), ref fCompany, value); }
        }
        int fProduct;
        public int Product
        {
            get { return fProduct; }
            set { SetPropertyValue<int>(nameof(Product), ref fProduct, value); }
        }
        int fCustomer;
        public int Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<int>(nameof(Customer), ref fCustomer, value); }
        }
        double fSalesQuantity;
        public double SalesQuantity
        {
            get { return fSalesQuantity; }
            set { SetPropertyValue<double>(nameof(SalesQuantity), ref fSalesQuantity, value); }
        }
        int fSource;
        public int Source
        {
            get { return fSource; }
            set { SetPropertyValue<int>(nameof(Source), ref fSource, value); }
        }
        int fDestination;
        public int Destination
        {
            get { return fDestination; }
            set { SetPropertyValue<int>(nameof(Destination), ref fDestination, value); }
        }
        int fMaterialType;
        public int MaterialType
        {
            get { return fMaterialType; }
            set { SetPropertyValue<int>(nameof(MaterialType), ref fMaterialType, value); }
        }
        int fPartType;
        public int PartType
        {
            get { return fPartType; }
            set { SetPropertyValue<int>(nameof(PartType), ref fPartType, value); }
        }
        int fPackType;
        public int PackType
        {
            get { return fPackType; }
            set { SetPropertyValue<int>(nameof(PackType), ref fPackType, value); }
        }
        int fCompRule;
        public int CompRule
        {
            get { return fCompRule; }
            set { SetPropertyValue<int>(nameof(CompRule), ref fCompRule, value); }
        }
        double fTonnes;
        public double Tonnes
        {
            get { return fTonnes; }
            set { SetPropertyValue<double>(nameof(Tonnes), ref fTonnes, value); }
        }
        double fWithSpec;
        public double WithSpec
        {
            get { return fWithSpec; }
            set { SetPropertyValue<double>(nameof(WithSpec), ref fWithSpec, value); }
        }
        int fMaterialCatery;
        [Persistent(@"MaterialCate ry")]
        public int MaterialCatery
        {
            get { return fMaterialCatery; }
            set { SetPropertyValue<int>(nameof(MaterialCatery), ref fMaterialCatery, value); }
        }
        double fRecycledTonnes;
        [ColumnDbDefaultValue("((0))")]
        public double RecycledTonnes
        {
            get { return fRecycledTonnes; }
            set { SetPropertyValue<double>(nameof(RecycledTonnes), ref fRecycledTonnes, value); }
        }
        double fRecyclableTonnes;
        public double RecyclableTonnes
        {
            get { return fRecyclableTonnes; }
            set { SetPropertyValue<double>(nameof(RecyclableTonnes), ref fRecyclableTonnes, value); }
        }
        DateTime fCalcDate;
        public DateTime CalcDate
        {
            get { return fCalcDate; }
            set { SetPropertyValue<DateTime>(nameof(CalcDate), ref fCalcDate, value); }
        }
        double fCompostableTonnes;
        public double CompostableTonnes
        {
            get { return fCompostableTonnes; }
            set { SetPropertyValue<double>(nameof(CompostableTonnes), ref fCompostableTonnes, value); }
        }
        double fNonRecyclableTonnes;
        public double NonRecyclableTonnes
        {
            get { return fNonRecyclableTonnes; }
            set { SetPropertyValue<double>(nameof(NonRecyclableTonnes), ref fNonRecyclableTonnes, value); }
        }
        int fMaterialCategory;
        public int MaterialCategory
        {
            get { return fMaterialCategory; }
            set { SetPropertyValue<int>(nameof(MaterialCategory), ref fMaterialCategory, value); }
        }
    }

}
