//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class FilteringCriterion : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        string fObjectType;
        public string ObjectType
        {
            get { return fObjectType; }
            set { SetPropertyValue<string>(nameof(ObjectType), ref fObjectType, value); }
        }
        string fCriteria;
        [Size(SizeAttribute.Unlimited)]
        public string Criteria
        {
            get { return fCriteria; }
            set { SetPropertyValue<string>(nameof(Criteria), ref fCriteria, value); }
        }
        string fCriterionPlusCriteriaRuleJson;
        [Size(SizeAttribute.Unlimited)]
        public string CriterionPlusCriteriaRuleJson
        {
            get { return fCriterionPlusCriteriaRuleJson; }
            set { SetPropertyValue<string>(nameof(CriterionPlusCriteriaRuleJson), ref fCriterionPlusCriteriaRuleJson, value); }
        }
        [Association(@"ComplianceRuleReferencesFilteringCriterion")]
        public XPCollection<ComplianceRule> ComplianceRules { get { return GetCollection<ComplianceRule>(nameof(ComplianceRules)); } }
    }

}
