//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class Group : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        int fParentId;
        public int ParentId
        {
            get { return fParentId; }
            set { SetPropertyValue<int>(nameof(ParentId), ref fParentId, value); }
        }
        Group fParent;
        [Association(@"GroupReferencesGroup")]
        public Group Parent
        {
            get { return fParent; }
            set { SetPropertyValue<Group>(nameof(Parent), ref fParent, value); }
        }
        [Association(@"GroupReferencesGroup")]
        public XPCollection<Group> GroupCollection { get { return GetCollection<Group>(nameof(GroupCollection)); } }
    }

}
