//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class IDASReturnCell : XPObject
    {
        string fTargetCell;
        public string TargetCell
        {
            get { return fTargetCell; }
            set { SetPropertyValue<string>(nameof(TargetCell), ref fTargetCell, value); }
        }
        EnumInstance fMaterialType;
        [Association(@"IDASReturnCellReferencesEnumInstance1")]
        public EnumInstance MaterialType
        {
            get { return fMaterialType; }
            set { SetPropertyValue<EnumInstance>(nameof(MaterialType), ref fMaterialType, value); }
        }
        EnumInstance fPackagingType;
        [Association(@"IDASReturnCellReferencesEnumInstance2")]
        public EnumInstance PackagingType
        {
            get { return fPackagingType; }
            set { SetPropertyValue<EnumInstance>(nameof(PackagingType), ref fPackagingType, value); }
        }
        EnumInstance fSource;
        [Association(@"IDASReturnCellReferencesEnumInstance3")]
        public EnumInstance Source
        {
            get { return fSource; }
            set { SetPropertyValue<EnumInstance>(nameof(Source), ref fSource, value); }
        }
        EnumInstance fDestination;
        [Association(@"IDASReturnCellReferencesEnumInstance")]
        public EnumInstance Destination
        {
            get { return fDestination; }
            set { SetPropertyValue<EnumInstance>(nameof(Destination), ref fDestination, value); }
        }
        double fAllocation;
        public double Allocation
        {
            get { return fAllocation; }
            set { SetPropertyValue<double>(nameof(Allocation), ref fAllocation, value); }
        }
        ComplianceRule fRule;
        [Association(@"IDASReturnCellReferencesComplianceRule")]
        public ComplianceRule Rule
        {
            get { return fRule; }
            set { SetPropertyValue<ComplianceRule>(nameof(Rule), ref fRule, value); }
        }
        IDASReturnLine fParentLine;
        [Association(@"IDASReturnCellReferencesIDASReturnLine")]
        public IDASReturnLine ParentLine
        {
            get { return fParentLine; }
            set { SetPropertyValue<IDASReturnLine>(nameof(ParentLine), ref fParentLine, value); }
        }
    }

}
