//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class IDASReturnLine : XPObject
    {
        int fLineID;
        public int LineID
        {
            get { return fLineID; }
            set { SetPropertyValue<int>(nameof(LineID), ref fLineID, value); }
        }
        string fReference;
        public string Reference
        {
            get { return fReference; }
            set { SetPropertyValue<string>(nameof(Reference), ref fReference, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        IDASReturnLine fParentLine;
        [Association(@"IDASReturnLineReferencesIDASReturnLine")]
        public IDASReturnLine ParentLine
        {
            get { return fParentLine; }
            set { SetPropertyValue<IDASReturnLine>(nameof(ParentLine), ref fParentLine, value); }
        }
        IDASReturn fParentReturn;
        [Association(@"IDASReturnLineReferencesIDASReturn")]
        public IDASReturn ParentReturn
        {
            get { return fParentReturn; }
            set { SetPropertyValue<IDASReturn>(nameof(ParentReturn), ref fParentReturn, value); }
        }
        [Association(@"IDASReturnCellReferencesIDASReturnLine")]
        public XPCollection<IDASReturnCell> IDASReturnCells { get { return GetCollection<IDASReturnCell>(nameof(IDASReturnCells)); } }
        [Association(@"IDASReturnLineReferencesIDASReturnLine")]
        public XPCollection<IDASReturnLine> IDASReturnLineCollection { get { return GetCollection<IDASReturnLine>(nameof(IDASReturnLineCollection)); } }
    }

}
