//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class ImportDefinition : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fTargetObjectType;
        public string TargetObjectType
        {
            get { return fTargetObjectType; }
            set { SetPropertyValue<string>(nameof(TargetObjectType), ref fTargetObjectType, value); }
        }
        bool fDataContainsHeaders;
        public bool DataContainsHeaders
        {
            get { return fDataContainsHeaders; }
            set { SetPropertyValue<bool>(nameof(DataContainsHeaders), ref fDataContainsHeaders, value); }
        }
        int fStartRow;
        public int StartRow
        {
            get { return fStartRow; }
            set { SetPropertyValue<int>(nameof(StartRow), ref fStartRow, value); }
        }
        int fStartColumn;
        public int StartColumn
        {
            get { return fStartColumn; }
            set { SetPropertyValue<int>(nameof(StartColumn), ref fStartColumn, value); }
        }
        int fImportMode;
        public int ImportMode
        {
            get { return fImportMode; }
            set { SetPropertyValue<int>(nameof(ImportMode), ref fImportMode, value); }
        }
        string fIdentifyRecordBy;
        [Size(SizeAttribute.Unlimited)]
        public string IdentifyRecordBy
        {
            get { return fIdentifyRecordBy; }
            set { SetPropertyValue<string>(nameof(IdentifyRecordBy), ref fIdentifyRecordBy, value); }
        }
        string fEmailTo;
        [Size(SizeAttribute.Unlimited)]
        public string EmailTo
        {
            get { return fEmailTo; }
            set { SetPropertyValue<string>(nameof(EmailTo), ref fEmailTo, value); }
        }
        ImportDefinitionCellMapping fEmailToMapping;
        [Association(@"ImportDefinitionReferencesImportDefinitionCellMapping")]
        public ImportDefinitionCellMapping EmailToMapping
        {
            get { return fEmailToMapping; }
            set { SetPropertyValue<ImportDefinitionCellMapping>(nameof(EmailToMapping), ref fEmailToMapping, value); }
        }
        string fRecordPostprocessCodeMethod;
        [Size(254)]
        public string RecordPostprocessCodeMethod
        {
            get { return fRecordPostprocessCodeMethod; }
            set { SetPropertyValue<string>(nameof(RecordPostprocessCodeMethod), ref fRecordPostprocessCodeMethod, value); }
        }
        string fImportPostprocessCodeMethod;
        [Size(254)]
        public string ImportPostprocessCodeMethod
        {
            get { return fImportPostprocessCodeMethod; }
            set { SetPropertyValue<string>(nameof(ImportPostprocessCodeMethod), ref fImportPostprocessCodeMethod, value); }
        }
        [Association(@"ImportDefinitionCellMappingReferencesImportDefinition")]
        public XPCollection<ImportDefinitionCellMapping> ImportDefinitionCellMappings { get { return GetCollection<ImportDefinitionCellMapping>(nameof(ImportDefinitionCellMappings)); } }
        [Association(@"ImportDefinitionColumnMappingReferencesImportDefinition")]
        public XPCollection<ImportDefinitionColumnMapping> ImportDefinitionColumnMappings { get { return GetCollection<ImportDefinitionColumnMapping>(nameof(ImportDefinitionColumnMappings)); } }
        [Association(@"ImportDefinitionFolderReferencesImportDefinition")]
        public XPCollection<ImportDefinitionFolder> ImportDefinitionFolders { get { return GetCollection<ImportDefinitionFolder>(nameof(ImportDefinitionFolders)); } }
        [Association(@"ImportLogReferencesImportDefinition")]
        public XPCollection<ImportLog> ImportLogs { get { return GetCollection<ImportLog>(nameof(ImportLogs)); } }
    }

}
