//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    [OptimisticLocking(false)]
    public partial class ImportCrossReference : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fRecordType;
        public string RecordType
        {
            get { return fRecordType; }
            set { SetPropertyValue<string>(nameof(RecordType), ref fRecordType, value); }
        }
        [Association(@"ImportCrossReferenceLineReferencesImportCrossReference")]
        public XPCollection<ImportCrossReferenceLine> ImportCrossReferenceLines { get { return GetCollection<ImportCrossReferenceLine>(nameof(ImportCrossReferenceLines)); } }
        [Association(@"ImportDefinitionCellMappingReferencesImportCrossReference")]
        public XPCollection<ImportDefinitionCellMapping> ImportDefinitionCellMappings { get { return GetCollection<ImportDefinitionCellMapping>(nameof(ImportDefinitionCellMappings)); } }
        [Association(@"ImportDefinitionColumnMappingReferencesImportCrossReference")]
        public XPCollection<ImportDefinitionColumnMapping> ImportDefinitionColumnMappings { get { return GetCollection<ImportDefinitionColumnMapping>(nameof(ImportDefinitionColumnMappings)); } }
    }

}
