//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class ImportLog : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        int fMostSevereLogType;
        public int MostSevereLogType
        {
            get { return fMostSevereLogType; }
            set { SetPropertyValue<int>(nameof(MostSevereLogType), ref fMostSevereLogType, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        string fLogDetails;
        [Size(SizeAttribute.Unlimited)]
        public string LogDetails
        {
            get { return fLogDetails; }
            set { SetPropertyValue<string>(nameof(LogDetails), ref fLogDetails, value); }
        }
        string fImportedFilePath;
        [Size(254)]
        public string ImportedFilePath
        {
            get { return fImportedFilePath; }
            set { SetPropertyValue<string>(nameof(ImportedFilePath), ref fImportedFilePath, value); }
        }
        int fModifiedObjects;
        public int ModifiedObjects
        {
            get { return fModifiedObjects; }
            set { SetPropertyValue<int>(nameof(ModifiedObjects), ref fModifiedObjects, value); }
        }
        string fEmailTo;
        public string EmailTo
        {
            get { return fEmailTo; }
            set { SetPropertyValue<string>(nameof(EmailTo), ref fEmailTo, value); }
        }
        ImportDefinition fImportDefinition;
        [Association(@"ImportLogReferencesImportDefinition")]
        public ImportDefinition ImportDefinition
        {
            get { return fImportDefinition; }
            set { SetPropertyValue<ImportDefinition>(nameof(ImportDefinition), ref fImportDefinition, value); }
        }
    }

}
