//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class KPIDEF : XPObject
    {
        int fParentID;
        public int ParentID
        {
            get { return fParentID; }
            set { SetPropertyValue<int>(nameof(ParentID), ref fParentID, value); }
        }
        string fReference;
        public string Reference
        {
            get { return fReference; }
            set { SetPropertyValue<string>(nameof(Reference), ref fReference, value); }
        }
        string fFieldName;
        public string FieldName
        {
            get { return fFieldName; }
            set { SetPropertyValue<string>(nameof(FieldName), ref fFieldName, value); }
        }
        string fFieldDesc;
        public string FieldDesc
        {
            get { return fFieldDesc; }
            set { SetPropertyValue<string>(nameof(FieldDesc), ref fFieldDesc, value); }
        }
        EnumInstance fFieldDataType;
        [Association(@"KPIDEFReferencesEnumInstance")]
        public EnumInstance FieldDataType
        {
            get { return fFieldDataType; }
            set { SetPropertyValue<EnumInstance>(nameof(FieldDataType), ref fFieldDataType, value); }
        }
        string fLookupData;
        public string LookupData
        {
            get { return fLookupData; }
            set { SetPropertyValue<string>(nameof(LookupData), ref fLookupData, value); }
        }
        string fDefaultData;
        public string DefaultData
        {
            get { return fDefaultData; }
            set { SetPropertyValue<string>(nameof(DefaultData), ref fDefaultData, value); }
        }
        int fSortId;
        public int SortId
        {
            get { return fSortId; }
            set { SetPropertyValue<int>(nameof(SortId), ref fSortId, value); }
        }
        int fFieldDecimal;
        public int FieldDecimal
        {
            get { return fFieldDecimal; }
            set { SetPropertyValue<int>(nameof(FieldDecimal), ref fFieldDecimal, value); }
        }
        int fFieldSize;
        public int FieldSize
        {
            get { return fFieldSize; }
            set { SetPropertyValue<int>(nameof(FieldSize), ref fFieldSize, value); }
        }
        Period fActiveFrom;
        [Association(@"KPIDEFReferencesPeriod")]
        public Period ActiveFrom
        {
            get { return fActiveFrom; }
            set { SetPropertyValue<Period>(nameof(ActiveFrom), ref fActiveFrom, value); }
        }
        Period fActiveTo;
        [Association(@"KPIDEFReferencesPeriod1")]
        public Period ActiveTo
        {
            get { return fActiveTo; }
            set { SetPropertyValue<Period>(nameof(ActiveTo), ref fActiveTo, value); }
        }
        [Association(@"KPIDATAReferencesKPIDEF")]
        public XPCollection<KPIDATA> KPIDATAs { get { return GetCollection<KPIDATA>(nameof(KPIDATAs)); } }
    }

}
