//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class KPIDATA : XPObject
    {
        double fNumValue;
        public double NumValue
        {
            get { return fNumValue; }
            set { SetPropertyValue<double>(nameof(NumValue), ref fNumValue, value); }
        }
        string fTxtValue;
        public string TxtValue
        {
            get { return fTxtValue; }
            set { SetPropertyValue<string>(nameof(TxtValue), ref fTxtValue, value); }
        }
        Period fActiveFrom;
        [Association(@"KPIDATAReferencesPeriod")]
        public Period ActiveFrom
        {
            get { return fActiveFrom; }
            set { SetPropertyValue<Period>(nameof(ActiveFrom), ref fActiveFrom, value); }
        }
        Period fActiveTo;
        [Association(@"KPIDATAReferencesPeriod1")]
        public Period ActiveTo
        {
            get { return fActiveTo; }
            set { SetPropertyValue<Period>(nameof(ActiveTo), ref fActiveTo, value); }
        }
        KPIDEF fKPIDef;
        [Association(@"KPIDATAReferencesKPIDEF")]
        public KPIDEF KPIDef
        {
            get { return fKPIDef; }
            set { SetPropertyValue<KPIDEF>(nameof(KPIDef), ref fKPIDef, value); }
        }
        KPIMEMO fMemo;
        [Association(@"KPIDATAReferencesKPIMEMO")]
        public KPIMEMO Memo
        {
            get { return fMemo; }
            set { SetPropertyValue<KPIMEMO>(nameof(Memo), ref fMemo, value); }
        }
    }

}
