//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class KPIMEMO : XPObject
    {
        byte[] fMemo;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Memo
        {
            get { return fMemo; }
            set { SetPropertyValue<byte[]>(nameof(Memo), ref fMemo, value); }
        }
        [Association(@"KPIDATAReferencesKPIMEMO")]
        public XPCollection<KPIDATA> KPIDATAs { get { return GetCollection<KPIDATA>(nameof(KPIDATAs)); } }
    }

}
