//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class Period : XPObject
    {
        DateTime fStartDate;
        public DateTime StartDate
        {
            get { return fStartDate; }
            set { SetPropertyValue<DateTime>(nameof(StartDate), ref fStartDate, value); }
        }
        DateTime fEndDate;
        public DateTime EndDate
        {
            get { return fEndDate; }
            set { SetPropertyValue<DateTime>(nameof(EndDate), ref fEndDate, value); }
        }
        bool fIsClosed;
        public bool IsClosed
        {
            get { return fIsClosed; }
            set { SetPropertyValue<bool>(nameof(IsClosed), ref fIsClosed, value); }
        }
        int fPeriodNum;
        public int PeriodNum
        {
            get { return fPeriodNum; }
            set { SetPropertyValue<int>(nameof(PeriodNum), ref fPeriodNum, value); }
        }
        bool fIsDataImp;
        public bool IsDataImp
        {
            get { return fIsDataImp; }
            set { SetPropertyValue<bool>(nameof(IsDataImp), ref fIsDataImp, value); }
        }
        bool fAreProdsUpd;
        public bool AreProdsUpd
        {
            get { return fAreProdsUpd; }
            set { SetPropertyValue<bool>(nameof(AreProdsUpd), ref fAreProdsUpd, value); }
        }
        bool fAreSpecsUpd;
        public bool AreSpecsUpd
        {
            get { return fAreSpecsUpd; }
            set { SetPropertyValue<bool>(nameof(AreSpecsUpd), ref fAreSpecsUpd, value); }
        }
        bool fAreRulesUpd;
        public bool AreRulesUpd
        {
            get { return fAreRulesUpd; }
            set { SetPropertyValue<bool>(nameof(AreRulesUpd), ref fAreRulesUpd, value); }
        }
        bool fAreRulesMap;
        public bool AreRulesMap
        {
            get { return fAreRulesMap; }
            set { SetPropertyValue<bool>(nameof(AreRulesMap), ref fAreRulesMap, value); }
        }
        bool fAreTonsCalc;
        public bool AreTonsCalc
        {
            get { return fAreTonsCalc; }
            set { SetPropertyValue<bool>(nameof(AreTonsCalc), ref fAreTonsCalc, value); }
        }
        bool fAreTonsExp;
        public bool AreTonsExp
        {
            get { return fAreTonsExp; }
            set { SetPropertyValue<bool>(nameof(AreTonsExp), ref fAreTonsExp, value); }
        }
        Company fCompany;
        [Association(@"PeriodReferencesCompany")]
        public Company Company
        {
            get { return fCompany; }
            set { SetPropertyValue<Company>(nameof(Company), ref fCompany, value); }
        }
        [Association(@"BOMReferencesPeriod")]
        public XPCollection<BOM> BOMs { get { return GetCollection<BOM>(nameof(BOMs)); } }
        [Association(@"BOMReferencesPeriod1")]
        public XPCollection<BOM> BOMs1 { get { return GetCollection<BOM>(nameof(BOMs1)); } }
        [Association(@"BOMItemReferencesPeriod")]
        public XPCollection<BOMItem> BOMItems { get { return GetCollection<BOMItem>(nameof(BOMItems)); } }
        [Association(@"BOMItemReferencesPeriod1")]
        public XPCollection<BOMItem> BOMItems1 { get { return GetCollection<BOMItem>(nameof(BOMItems1)); } }
        [Association(@"ComplianceRuleReferencesPeriod")]
        public XPCollection<ComplianceRule> ComplianceRules { get { return GetCollection<ComplianceRule>(nameof(ComplianceRules)); } }
        [Association(@"ComplianceRuleReferencesPeriod1")]
        public XPCollection<ComplianceRule> ComplianceRules1 { get { return GetCollection<ComplianceRule>(nameof(ComplianceRules1)); } }
        [Association(@"CustomerReferencesPeriod")]
        public XPCollection<Customer> Customers { get { return GetCollection<Customer>(nameof(Customers)); } }
        [Association(@"CustomerReferencesPeriod1")]
        public XPCollection<Customer> Customers1 { get { return GetCollection<Customer>(nameof(Customers1)); } }
        [Association(@"DimCustomerReferencesPeriod")]
        public XPCollection<DimCustomer> DimCustomers { get { return GetCollection<DimCustomer>(nameof(DimCustomers)); } }
        [Association(@"DimCustomerReferencesPeriod1")]
        public XPCollection<DimCustomer> DimCustomers1 { get { return GetCollection<DimCustomer>(nameof(DimCustomers1)); } }
        [Association(@"DimItemTypeReferencesPeriod")]
        public XPCollection<DimItemType> DimItemTypes { get { return GetCollection<DimItemType>(nameof(DimItemTypes)); } }
        [Association(@"DimItemTypeReferencesPeriod1")]
        public XPCollection<DimItemType> DimItemTypes1 { get { return GetCollection<DimItemType>(nameof(DimItemTypes1)); } }
        [Association(@"DimMaterialReferencesPeriod")]
        public XPCollection<DimMaterial> DimMaterials { get { return GetCollection<DimMaterial>(nameof(DimMaterials)); } }
        [Association(@"DimMaterialReferencesPeriod1")]
        public XPCollection<DimMaterial> DimMaterials1 { get { return GetCollection<DimMaterial>(nameof(DimMaterials1)); } }
        [Association(@"DimPartTypeReferencesPeriod")]
        public XPCollection<DimPartType> DimPartTypes { get { return GetCollection<DimPartType>(nameof(DimPartTypes)); } }
        [Association(@"DimPartTypeReferencesPeriod1")]
        public XPCollection<DimPartType> DimPartTypes1 { get { return GetCollection<DimPartType>(nameof(DimPartTypes1)); } }
        [Association(@"DimProductReferencesPeriod")]
        public XPCollection<DimProduct> DimProducts { get { return GetCollection<DimProduct>(nameof(DimProducts)); } }
        [Association(@"DimProductReferencesPeriod1")]
        public XPCollection<DimProduct> DimProducts1 { get { return GetCollection<DimProduct>(nameof(DimProducts1)); } }
        [Association(@"EnumDomainReferencesPeriod")]
        public XPCollection<EnumDomain> EnumDomains { get { return GetCollection<EnumDomain>(nameof(EnumDomains)); } }
        [Association(@"EnumDomainReferencesPeriod1")]
        public XPCollection<EnumDomain> EnumDomains1 { get { return GetCollection<EnumDomain>(nameof(EnumDomains1)); } }
        [Association(@"EnumDomainSubsetReferencesPeriod")]
        public XPCollection<EnumDomainSubset> EnumDomainSubsets { get { return GetCollection<EnumDomainSubset>(nameof(EnumDomainSubsets)); } }
        [Association(@"EnumDomainSubsetReferencesPeriod1")]
        public XPCollection<EnumDomainSubset> EnumDomainSubsets1 { get { return GetCollection<EnumDomainSubset>(nameof(EnumDomainSubsets1)); } }
        [Association(@"EnumDomSubItemReferencesPeriod")]
        public XPCollection<EnumDomSubItem> EnumDomSubItems { get { return GetCollection<EnumDomSubItem>(nameof(EnumDomSubItems)); } }
        [Association(@"EnumDomSubItemReferencesPeriod1")]
        public XPCollection<EnumDomSubItem> EnumDomSubItems1 { get { return GetCollection<EnumDomSubItem>(nameof(EnumDomSubItems1)); } }
        [Association(@"EnumInstanceReferencesPeriod")]
        public XPCollection<EnumInstance> EnumInstances { get { return GetCollection<EnumInstance>(nameof(EnumInstances)); } }
        [Association(@"EnumInstanceReferencesPeriod1")]
        public XPCollection<EnumInstance> EnumInstances1 { get { return GetCollection<EnumInstance>(nameof(EnumInstances1)); } }
        [Association(@"FactPrimaryEndOfLifeReferencesPeriod")]
        public XPCollection<FactPrimaryEndOfLife> FactPrimaryEndOfLives { get { return GetCollection<FactPrimaryEndOfLife>(nameof(FactPrimaryEndOfLives)); } }
        [Association(@"FactPrimaryEndOfLifeReferencesPeriod1")]
        public XPCollection<FactPrimaryEndOfLife> FactPrimaryEndOfLives1 { get { return GetCollection<FactPrimaryEndOfLife>(nameof(FactPrimaryEndOfLives1)); } }
        [Association(@"FactSUPItemsReferencesPeriod")]
        public XPCollection<FactSUPItems> FactSUPItemsCollection { get { return GetCollection<FactSUPItems>(nameof(FactSUPItemsCollection)); } }
        [Association(@"FactSUPItemsReferencesPeriod1")]
        public XPCollection<FactSUPItems> FactSUPItemsCollection1 { get { return GetCollection<FactSUPItems>(nameof(FactSUPItemsCollection1)); } }
        [Association(@"IDASPackTotalReferencesPeriod")]
        public XPCollection<IDASPackTotal> IDASPackTotals { get { return GetCollection<IDASPackTotal>(nameof(IDASPackTotals)); } }
        [Association(@"IDASPackTotalReferencesPeriod1")]
        public XPCollection<IDASPackTotal> IDASPackTotals1 { get { return GetCollection<IDASPackTotal>(nameof(IDASPackTotals1)); } }
        [Association(@"KPIDATAReferencesPeriod")]
        public XPCollection<KPIDATA> KPIDATAs { get { return GetCollection<KPIDATA>(nameof(KPIDATAs)); } }
        [Association(@"KPIDATAReferencesPeriod1")]
        public XPCollection<KPIDATA> KPIDATAs1 { get { return GetCollection<KPIDATA>(nameof(KPIDATAs1)); } }
        [Association(@"KPIDEFReferencesPeriod")]
        public XPCollection<KPIDEF> KPIDEFs { get { return GetCollection<KPIDEF>(nameof(KPIDEFs)); } }
        [Association(@"KPIDEFReferencesPeriod1")]
        public XPCollection<KPIDEF> KPIDEFs1 { get { return GetCollection<KPIDEF>(nameof(KPIDEFs1)); } }
        [Association(@"MaterialMappingReferencesPeriod")]
        public XPCollection<MaterialMapping> MaterialMappings { get { return GetCollection<MaterialMapping>(nameof(MaterialMappings)); } }
        [Association(@"MaterialMappingReferencesPeriod1")]
        public XPCollection<MaterialMapping> MaterialMappings1 { get { return GetCollection<MaterialMapping>(nameof(MaterialMappings1)); } }
        [Association(@"PartReferencesPeriod")]
        public XPCollection<Part> Parts { get { return GetCollection<Part>(nameof(Parts)); } }
        [Association(@"PartReferencesPeriod1")]
        public XPCollection<Part> Parts1 { get { return GetCollection<Part>(nameof(Parts1)); } }
        [Association(@"ProductReferencesPeriod")]
        public XPCollection<Product> Products { get { return GetCollection<Product>(nameof(Products)); } }
        [Association(@"ProductReferencesPeriod1")]
        public XPCollection<Product> Products1 { get { return GetCollection<Product>(nameof(Products1)); } }
        [Association(@"RepakReturnCellReferencesPeriod")]
        public XPCollection<RepakReturnCell> RepakReturnCells { get { return GetCollection<RepakReturnCell>(nameof(RepakReturnCells)); } }
        [Association(@"RepakReturnCellReferencesPeriod1")]
        public XPCollection<RepakReturnCell> RepakReturnCells1 { get { return GetCollection<RepakReturnCell>(nameof(RepakReturnCells1)); } }
        [Association(@"RuleItemReferencesPeriod")]
        public XPCollection<RuleItem> RuleItems { get { return GetCollection<RuleItem>(nameof(RuleItems)); } }
        [Association(@"RuleItemReferencesPeriod1")]
        public XPCollection<RuleItem> RuleItems1 { get { return GetCollection<RuleItem>(nameof(RuleItems1)); } }
        [Association(@"SalesVolumeReferencesPeriod")]
        public XPCollection<SalesVolume> SalesVolumes { get { return GetCollection<SalesVolume>(nameof(SalesVolumes)); } }
        [Association(@"SalesVolumeReferencesPeriod1")]
        public XPCollection<SalesVolume> SalesVolumes1 { get { return GetCollection<SalesVolume>(nameof(SalesVolumes1)); } }
        [Association(@"SampleReferencesPeriod")]
        public XPCollection<Sample> Samples { get { return GetCollection<Sample>(nameof(Samples)); } }
        [Association(@"SRAttributeReferencesPeriod")]
        public XPCollection<SRAttribute> SRAttributes { get { return GetCollection<SRAttribute>(nameof(SRAttributes)); } }
        [Association(@"SRAttributeReferencesPeriod1")]
        public XPCollection<SRAttribute> SRAttributes1 { get { return GetCollection<SRAttribute>(nameof(SRAttributes1)); } }
        [Association(@"SupplierReferencesPeriod")]
        public XPCollection<Supplier> Suppliers { get { return GetCollection<Supplier>(nameof(Suppliers)); } }
        [Association(@"SupplierReferencesPeriod1")]
        public XPCollection<Supplier> Suppliers1 { get { return GetCollection<Supplier>(nameof(Suppliers1)); } }
        [Association(@"TotalPackWeightReferencesPeriod")]
        public XPCollection<TotalPackWeight> TotalPackWeights { get { return GetCollection<TotalPackWeight>(nameof(TotalPackWeights)); } }
        [Association(@"TotalPackWeightReferencesPeriod1")]
        public XPCollection<TotalPackWeight> TotalPackWeights1 { get { return GetCollection<TotalPackWeight>(nameof(TotalPackWeights1)); } }
        [Association(@"UKReturnCellReferencesPeriod")]
        public XPCollection<UKReturnCell> UKReturnCells { get { return GetCollection<UKReturnCell>(nameof(UKReturnCells)); } }
        [Association(@"UKReturnCellReferencesPeriod1")]
        public XPCollection<UKReturnCell> UKReturnCells1 { get { return GetCollection<UKReturnCell>(nameof(UKReturnCells1)); } }
    }

}
