//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class ProductGroup : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        int fParentId;
        public int ParentId
        {
            get { return fParentId; }
            set { SetPropertyValue<int>(nameof(ParentId), ref fParentId, value); }
        }
        string fClientId;
        public string ClientId
        {
            get { return fClientId; }
            set { SetPropertyValue<string>(nameof(ClientId), ref fClientId, value); }
        }
        string fClientParentId;
        public string ClientParentId
        {
            get { return fClientParentId; }
            set { SetPropertyValue<string>(nameof(ClientParentId), ref fClientParentId, value); }
        }
        int fGroupType;
        public int GroupType
        {
            get { return fGroupType; }
            set { SetPropertyValue<int>(nameof(GroupType), ref fGroupType, value); }
        }
        int fClientGrpType;
        public int ClientGrpType
        {
            get { return fClientGrpType; }
            set { SetPropertyValue<int>(nameof(ClientGrpType), ref fClientGrpType, value); }
        }
        ProductGroup fParent;
        [Association(@"ProductGroupReferencesProductGroup")]
        public ProductGroup Parent
        {
            get { return fParent; }
            set { SetPropertyValue<ProductGroup>(nameof(Parent), ref fParent, value); }
        }
        Company fCompany;
        [Association(@"ProductGroupReferencesCompany")]
        public Company Company
        {
            get { return fCompany; }
            set { SetPropertyValue<Company>(nameof(Company), ref fCompany, value); }
        }
        [Association(@"ProductReferencesProductGroup")]
        public XPCollection<Product> Products { get { return GetCollection<Product>(nameof(Products)); } }
        [Association(@"ProductGroupReferencesProductGroup")]
        public XPCollection<ProductGroup> ProductGroupCollection { get { return GetCollection<ProductGroup>(nameof(ProductGroupCollection)); } }
        [Association(@"SampleCateryReferencesProductGroup")]
        public XPCollection<SampleCatery> SampleCateries { get { return GetCollection<SampleCatery>(nameof(SampleCateries)); } }
        [Association(@"SampleCategoryReferencesProductGroup")]
        public XPCollection<SampleCategory> SampleCategories { get { return GetCollection<SampleCategory>(nameof(SampleCategories)); } }
    }

}
