//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class ProdWeight : XPObject
    {
        decimal fQuantity;
        public decimal Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<decimal>(nameof(Quantity), ref fQuantity, value); }
        }
        int fUnitOfMeas;
        public int UnitOfMeas
        {
            get { return fUnitOfMeas; }
            set { SetPropertyValue<int>(nameof(UnitOfMeas), ref fUnitOfMeas, value); }
        }
        EnumInstance fType;
        [Association(@"ProdWeightReferencesEnumInstance")]
        public EnumInstance Type
        {
            get { return fType; }
            set { SetPropertyValue<EnumInstance>(nameof(Type), ref fType, value); }
        }
        Part fPart;
        [Association(@"ProdWeightReferencesPart")]
        public Part Part
        {
            get { return fPart; }
            set { SetPropertyValue<Part>(nameof(Part), ref fPart, value); }
        }
        BOM fBOM;
        [Association(@"ProdWeightReferencesBOM")]
        public BOM BOM
        {
            get { return fBOM; }
            set { SetPropertyValue<BOM>(nameof(BOM), ref fBOM, value); }
        }
        [Association(@"BOMReferencesProdWeight")]
        public XPCollection<BOM> BOMs { get { return GetCollection<BOM>(nameof(BOMs)); } }
    }

}
