//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class RepakReturnLineFilter : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fFilter;
        public string Filter
        {
            get { return fFilter; }
            set { SetPropertyValue<string>(nameof(Filter), ref fFilter, value); }
        }
        RepakReturnLine fLine;
        [Association(@"RepakReturnLineFilterReferencesRepakReturnLine")]
        public RepakReturnLine Line
        {
            get { return fLine; }
            set { SetPropertyValue<RepakReturnLine>(nameof(Line), ref fLine, value); }
        }
    }

}
