//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class RepakReturnCell : XPObject
    {
        string fTargetCell;
        public string TargetCell
        {
            get { return fTargetCell; }
            set { SetPropertyValue<string>(nameof(TargetCell), ref fTargetCell, value); }
        }
        int fMaterialType;
        public int MaterialType
        {
            get { return fMaterialType; }
            set { SetPropertyValue<int>(nameof(MaterialType), ref fMaterialType, value); }
        }
        RepakReturnLine fParentLine;
        [Association(@"RepakReturnCellReferencesRepakReturnLine")]
        public RepakReturnLine ParentLine
        {
            get { return fParentLine; }
            set { SetPropertyValue<RepakReturnLine>(nameof(ParentLine), ref fParentLine, value); }
        }
        int fPackagingType;
        public int PackagingType
        {
            get { return fPackagingType; }
            set { SetPropertyValue<int>(nameof(PackagingType), ref fPackagingType, value); }
        }
        int fDestination;
        public int Destination
        {
            get { return fDestination; }
            set { SetPropertyValue<int>(nameof(Destination), ref fDestination, value); }
        }
        double fAllocation;
        public double Allocation
        {
            get { return fAllocation; }
            set { SetPropertyValue<double>(nameof(Allocation), ref fAllocation, value); }
        }
        int fCompRule;
        public int CompRule
        {
            get { return fCompRule; }
            set { SetPropertyValue<int>(nameof(CompRule), ref fCompRule, value); }
        }
        int fSource;
        public int Source
        {
            get { return fSource; }
            set { SetPropertyValue<int>(nameof(Source), ref fSource, value); }
        }
        ComplianceRule fRule;
        [Association(@"RepakReturnCellReferencesComplianceRule")]
        public ComplianceRule Rule
        {
            get { return fRule; }
            set { SetPropertyValue<ComplianceRule>(nameof(Rule), ref fRule, value); }
        }
        int fMaterialCatery;
        [Persistent(@"MaterialCate ry")]
        public int MaterialCatery
        {
            get { return fMaterialCatery; }
            set { SetPropertyValue<int>(nameof(MaterialCatery), ref fMaterialCatery, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        DateTime fLastChangedOn;
        public DateTime LastChangedOn
        {
            get { return fLastChangedOn; }
            set { SetPropertyValue<DateTime>(nameof(LastChangedOn), ref fLastChangedOn, value); }
        }
        User fCreatedBy;
        [Association(@"RepakReturnCellReferencesUser")]
        public User CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<User>(nameof(CreatedBy), ref fCreatedBy, value); }
        }
        User fLastChangedBy;
        [Association(@"RepakReturnCellReferencesUser1")]
        public User LastChangedBy
        {
            get { return fLastChangedBy; }
            set { SetPropertyValue<User>(nameof(LastChangedBy), ref fLastChangedBy, value); }
        }
        Period fActiveFrom;
        [Association(@"RepakReturnCellReferencesPeriod")]
        public Period ActiveFrom
        {
            get { return fActiveFrom; }
            set { SetPropertyValue<Period>(nameof(ActiveFrom), ref fActiveFrom, value); }
        }
        Period fActiveTo;
        [Association(@"RepakReturnCellReferencesPeriod1")]
        public Period ActiveTo
        {
            get { return fActiveTo; }
            set { SetPropertyValue<Period>(nameof(ActiveTo), ref fActiveTo, value); }
        }
        Company fCompany;
        [Association(@"RepakReturnCellReferencesCompany")]
        public Company Company
        {
            get { return fCompany; }
            set { SetPropertyValue<Company>(nameof(Company), ref fCompany, value); }
        }
        int fMaterialCategory;
        public int MaterialCategory
        {
            get { return fMaterialCategory; }
            set { SetPropertyValue<int>(nameof(MaterialCategory), ref fMaterialCategory, value); }
        }
    }

}
