//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class SalesVolume : XPObject
    {
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        DateTime fLastChangedOn;
        public DateTime LastChangedOn
        {
            get { return fLastChangedOn; }
            set { SetPropertyValue<DateTime>(nameof(LastChangedOn), ref fLastChangedOn, value); }
        }
        int fCreatedBy;
        public int CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<int>(nameof(CreatedBy), ref fCreatedBy, value); }
        }
        int fLastChangedBy;
        public int LastChangedBy
        {
            get { return fLastChangedBy; }
            set { SetPropertyValue<int>(nameof(LastChangedBy), ref fLastChangedBy, value); }
        }
        Period fActiveFrom;
        [Association(@"SalesVolumeReferencesPeriod")]
        public Period ActiveFrom
        {
            get { return fActiveFrom; }
            set { SetPropertyValue<Period>(nameof(ActiveFrom), ref fActiveFrom, value); }
        }
        Period fActiveTo;
        [Association(@"SalesVolumeReferencesPeriod1")]
        public Period ActiveTo
        {
            get { return fActiveTo; }
            set { SetPropertyValue<Period>(nameof(ActiveTo), ref fActiveTo, value); }
        }
        decimal fVolume;
        public decimal Volume
        {
            get { return fVolume; }
            set { SetPropertyValue<decimal>(nameof(Volume), ref fVolume, value); }
        }
        int fVolumeType;
        public int VolumeType
        {
            get { return fVolumeType; }
            set { SetPropertyValue<int>(nameof(VolumeType), ref fVolumeType, value); }
        }
        int fGroupId;
        public int GroupId
        {
            get { return fGroupId; }
            set { SetPropertyValue<int>(nameof(GroupId), ref fGroupId, value); }
        }
        Product fProduct;
        [Association(@"SalesVolumeReferencesProduct")]
        public Product Product
        {
            get { return fProduct; }
            set { SetPropertyValue<Product>(nameof(Product), ref fProduct, value); }
        }
        ComplianceRule fRule;
        [Association(@"SalesVolumeReferencesComplianceRule")]
        public ComplianceRule Rule
        {
            get { return fRule; }
            set { SetPropertyValue<ComplianceRule>(nameof(Rule), ref fRule, value); }
        }
        Customer fCustomer;
        [Association(@"SalesVolumeReferencesCustomer")]
        public Customer Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<Customer>(nameof(Customer), ref fCustomer, value); }
        }
        BOM fBOM;
        [Association(@"SalesVolumeReferencesBOM")]
        public BOM BOM
        {
            get { return fBOM; }
            set { SetPropertyValue<BOM>(nameof(BOM), ref fBOM, value); }
        }
        decimal fValue;
        public decimal Value
        {
            get { return fValue; }
            set { SetPropertyValue<decimal>(nameof(Value), ref fValue, value); }
        }
        Company fCompany;
        [Association(@"SalesVolumeReferencesCompany")]
        public Company Company
        {
            get { return fCompany; }
            set { SetPropertyValue<Company>(nameof(Company), ref fCompany, value); }
        }
    }

}
