//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class SampleCoefficient : XPObject
    {
        EnumInstance fSource;
        [Association(@"SampleCoefficientReferencesEnumInstance3")]
        public EnumInstance Source
        {
            get { return fSource; }
            set { SetPropertyValue<EnumInstance>(nameof(Source), ref fSource, value); }
        }
        EnumInstance fMaterial;
        [Association(@"SampleCoefficientReferencesEnumInstance")]
        public EnumInstance Material
        {
            get { return fMaterial; }
            set { SetPropertyValue<EnumInstance>(nameof(Material), ref fMaterial, value); }
        }
        EnumInstance fPackType;
        [Association(@"SampleCoefficientReferencesEnumInstance2")]
        public EnumInstance PackType
        {
            get { return fPackType; }
            set { SetPropertyValue<EnumInstance>(nameof(PackType), ref fPackType, value); }
        }
        double fTonnes;
        public double Tonnes
        {
            get { return fTonnes; }
            set { SetPropertyValue<double>(nameof(Tonnes), ref fTonnes, value); }
        }
        SampleCatery fCatery;
        [Persistent(@"Cate ry")]
        [Association(@"SampleCoefficientReferencesSampleCatery")]
        public SampleCatery Catery
        {
            get { return fCatery; }
            set { SetPropertyValue<SampleCatery>(nameof(Catery), ref fCatery, value); }
        }
        EnumInstance fMaterialCatery;
        [Persistent(@"MaterialCate ry")]
        [Association(@"SampleCoefficientReferencesEnumInstance1")]
        public EnumInstance MaterialCatery
        {
            get { return fMaterialCatery; }
            set { SetPropertyValue<EnumInstance>(nameof(MaterialCatery), ref fMaterialCatery, value); }
        }
        double fAvgTonnes;
        public double AvgTonnes
        {
            get { return fAvgTonnes; }
            set { SetPropertyValue<double>(nameof(AvgTonnes), ref fAvgTonnes, value); }
        }
        double fMOETonnes;
        public double MOETonnes
        {
            get { return fMOETonnes; }
            set { SetPropertyValue<double>(nameof(MOETonnes), ref fMOETonnes, value); }
        }
        SampleCategory fCategory;
        [Association(@"SampleCoefficientReferencesSampleCategory")]
        public SampleCategory Category
        {
            get { return fCategory; }
            set { SetPropertyValue<SampleCategory>(nameof(Category), ref fCategory, value); }
        }
        int fMaterialCategory;
        public int MaterialCategory
        {
            get { return fMaterialCategory; }
            set { SetPropertyValue<int>(nameof(MaterialCategory), ref fMaterialCategory, value); }
        }
    }

}
