//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class SampleCategory : XPObject
    {
        ProductGroup fProductGroup;
        [Association(@"SampleCategoryReferencesProductGroup")]
        public ProductGroup ProductGroup
        {
            get { return fProductGroup; }
            set { SetPropertyValue<ProductGroup>(nameof(ProductGroup), ref fProductGroup, value); }
        }
        double fTotal;
        public double Total
        {
            get { return fTotal; }
            set { SetPropertyValue<double>(nameof(Total), ref fTotal, value); }
        }
        int fSampleSize;
        public int SampleSize
        {
            get { return fSampleSize; }
            set { SetPropertyValue<int>(nameof(SampleSize), ref fSampleSize, value); }
        }
        Sample fSample;
        [Association(@"SampleCategoryReferencesSample")]
        public Sample Sample
        {
            get { return fSample; }
            set { SetPropertyValue<Sample>(nameof(Sample), ref fSample, value); }
        }
        [Association(@"SampleCoefficientReferencesSampleCategory")]
        public XPCollection<SampleCoefficient> SampleCoefficients { get { return GetCollection<SampleCoefficient>(nameof(SampleCoefficients)); } }
        [Association(@"SampleItemReferencesSampleCategory")]
        public XPCollection<SampleItem> SampleItems { get { return GetCollection<SampleItem>(nameof(SampleItems)); } }
        [Association(@"SamplePackWeightReferencesSampleCategory")]
        public XPCollection<SamplePackWeight> SamplePackWeights { get { return GetCollection<SamplePackWeight>(nameof(SamplePackWeights)); } }
    }

}
