//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class SRAttribute : XPObject
    {
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        DateTime fLastChangedOn;
        public DateTime LastChangedOn
        {
            get { return fLastChangedOn; }
            set { SetPropertyValue<DateTime>(nameof(LastChangedOn), ref fLastChangedOn, value); }
        }
        User fCreatedBy;
        [Association(@"SRAttributeReferencesUser")]
        public User CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<User>(nameof(CreatedBy), ref fCreatedBy, value); }
        }
        User fLastChangedBy;
        [Association(@"SRAttributeReferencesUser1")]
        public User LastChangedBy
        {
            get { return fLastChangedBy; }
            set { SetPropertyValue<User>(nameof(LastChangedBy), ref fLastChangedBy, value); }
        }
        Period fActiveFrom;
        [Association(@"SRAttributeReferencesPeriod")]
        public Period ActiveFrom
        {
            get { return fActiveFrom; }
            set { SetPropertyValue<Period>(nameof(ActiveFrom), ref fActiveFrom, value); }
        }
        Period fActiveTo;
        [Association(@"SRAttributeReferencesPeriod1")]
        public Period ActiveTo
        {
            get { return fActiveTo; }
            set { SetPropertyValue<Period>(nameof(ActiveTo), ref fActiveTo, value); }
        }
        Company fCompany;
        [Association(@"SRAttributeReferencesCompany")]
        public Company Company
        {
            get { return fCompany; }
            set { SetPropertyValue<Company>(nameof(Company), ref fCompany, value); }
        }
        string fAttributeText;
        public string AttributeText
        {
            get { return fAttributeText; }
            set { SetPropertyValue<string>(nameof(AttributeText), ref fAttributeText, value); }
        }
        double fAttributeNum;
        public double AttributeNum
        {
            get { return fAttributeNum; }
            set { SetPropertyValue<double>(nameof(AttributeNum), ref fAttributeNum, value); }
        }
        int fReportType;
        public int ReportType
        {
            get { return fReportType; }
            set { SetPropertyValue<int>(nameof(ReportType), ref fReportType, value); }
        }
        int fAttributeName;
        public int AttributeName
        {
            get { return fAttributeName; }
            set { SetPropertyValue<int>(nameof(AttributeName), ref fAttributeName, value); }
        }
        Part fComponent;
        [Association(@"SRAttributeReferencesPart")]
        public Part Component
        {
            get { return fComponent; }
            set { SetPropertyValue<Part>(nameof(Component), ref fComponent, value); }
        }
    }

}
