//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class SupplierGroup : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        int fParentId;
        public int ParentId
        {
            get { return fParentId; }
            set { SetPropertyValue<int>(nameof(ParentId), ref fParentId, value); }
        }
        SupplierGroup fParent;
        [Association(@"SupplierGroupReferencesSupplierGroup")]
        public SupplierGroup Parent
        {
            get { return fParent; }
            set { SetPropertyValue<SupplierGroup>(nameof(Parent), ref fParent, value); }
        }
        Company fCompany;
        [Association(@"SupplierGroupReferencesCompany")]
        public Company Company
        {
            get { return fCompany; }
            set { SetPropertyValue<Company>(nameof(Company), ref fCompany, value); }
        }
        [Association(@"SupplierReferencesSupplierGroup")]
        public XPCollection<Supplier> Suppliers { get { return GetCollection<Supplier>(nameof(Suppliers)); } }
        [Association(@"SupplierGroupReferencesSupplierGroup")]
        public XPCollection<SupplierGroup> SupplierGroupCollection { get { return GetCollection<SupplierGroup>(nameof(SupplierGroupCollection)); } }
    }

}
