//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class SupplierContact : XPObject
    {
        string fPhone;
        public string Phone
        {
            get { return fPhone; }
            set { SetPropertyValue<string>(nameof(Phone), ref fPhone, value); }
        }
        string fFax;
        public string Fax
        {
            get { return fFax; }
            set { SetPropertyValue<string>(nameof(Fax), ref fFax, value); }
        }
        string fEmail;
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        string fWeb;
        public string Web
        {
            get { return fWeb; }
            set { SetPropertyValue<string>(nameof(Web), ref fWeb, value); }
        }
        string fContactName;
        public string ContactName
        {
            get { return fContactName; }
            set { SetPropertyValue<string>(nameof(ContactName), ref fContactName, value); }
        }
        Supplier fSupplier;
        [Association(@"SupplierContactReferencesSupplier")]
        public Supplier Supplier
        {
            get { return fSupplier; }
            set { SetPropertyValue<Supplier>(nameof(Supplier), ref fSupplier, value); }
        }
    }

}
