//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class TotalPackWeight : XPObject
    {
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        DateTime fLastChangedOn;
        public DateTime LastChangedOn
        {
            get { return fLastChangedOn; }
            set { SetPropertyValue<DateTime>(nameof(LastChangedOn), ref fLastChangedOn, value); }
        }
        User fCreatedBy;
        [Association(@"TotalPackWeightReferencesUser")]
        public User CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<User>(nameof(CreatedBy), ref fCreatedBy, value); }
        }
        User fLastChangedBy;
        [Association(@"TotalPackWeightReferencesUser1")]
        public User LastChangedBy
        {
            get { return fLastChangedBy; }
            set { SetPropertyValue<User>(nameof(LastChangedBy), ref fLastChangedBy, value); }
        }
        Period fActiveFrom;
        [Association(@"TotalPackWeightReferencesPeriod")]
        public Period ActiveFrom
        {
            get { return fActiveFrom; }
            set { SetPropertyValue<Period>(nameof(ActiveFrom), ref fActiveFrom, value); }
        }
        Period fActiveTo;
        [Association(@"TotalPackWeightReferencesPeriod1")]
        public Period ActiveTo
        {
            get { return fActiveTo; }
            set { SetPropertyValue<Period>(nameof(ActiveTo), ref fActiveTo, value); }
        }
        int fSource;
        public int Source
        {
            get { return fSource; }
            set { SetPropertyValue<int>(nameof(Source), ref fSource, value); }
        }
        int fDestination;
        public int Destination
        {
            get { return fDestination; }
            set { SetPropertyValue<int>(nameof(Destination), ref fDestination, value); }
        }
        int fMaterialType;
        public int MaterialType
        {
            get { return fMaterialType; }
            set { SetPropertyValue<int>(nameof(MaterialType), ref fMaterialType, value); }
        }
        int fPackType;
        public int PackType
        {
            get { return fPackType; }
            set { SetPropertyValue<int>(nameof(PackType), ref fPackType, value); }
        }
        ComplianceRule fCompRule;
        [Association(@"TotalPackWeightReferencesComplianceRule")]
        public ComplianceRule CompRule
        {
            get { return fCompRule; }
            set { SetPropertyValue<ComplianceRule>(nameof(CompRule), ref fCompRule, value); }
        }
        double fTonnes;
        public double Tonnes
        {
            get { return fTonnes; }
            set { SetPropertyValue<double>(nameof(Tonnes), ref fTonnes, value); }
        }
        double fWithSpec;
        public double WithSpec
        {
            get { return fWithSpec; }
            set { SetPropertyValue<double>(nameof(WithSpec), ref fWithSpec, value); }
        }
        int fMaterialCatery;
        [Persistent(@"MaterialCate ry")]
        public int MaterialCatery
        {
            get { return fMaterialCatery; }
            set { SetPropertyValue<int>(nameof(MaterialCatery), ref fMaterialCatery, value); }
        }
        Company fCompany;
        [Association(@"TotalPackWeightReferencesCompany")]
        public Company Company
        {
            get { return fCompany; }
            set { SetPropertyValue<Company>(nameof(Company), ref fCompany, value); }
        }
        int fSRAttrName;
        public int SRAttrName
        {
            get { return fSRAttrName; }
            set { SetPropertyValue<int>(nameof(SRAttrName), ref fSRAttrName, value); }
        }
        double fTotalSales;
        public double TotalSales
        {
            get { return fTotalSales; }
            set { SetPropertyValue<double>(nameof(TotalSales), ref fTotalSales, value); }
        }
        int fSRReportType;
        public int SRReportType
        {
            get { return fSRReportType; }
            set { SetPropertyValue<int>(nameof(SRReportType), ref fSRReportType, value); }
        }
        int fMaterialCategory;
        public int MaterialCategory
        {
            get { return fMaterialCategory; }
            set { SetPropertyValue<int>(nameof(MaterialCategory), ref fMaterialCategory, value); }
        }
    }

}
