//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class UpdateScriptResult : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        Guid fUpdateID;
        public Guid UpdateID
        {
            get { return fUpdateID; }
            set { SetPropertyValue<Guid>(nameof(UpdateID), ref fUpdateID, value); }
        }
        string fUpdateDescription;
        [Size(1024)]
        public string UpdateDescription
        {
            get { return fUpdateDescription; }
            set { SetPropertyValue<string>(nameof(UpdateDescription), ref fUpdateDescription, value); }
        }
        DateTime fCreatedDate;
        public DateTime CreatedDate
        {
            get { return fCreatedDate; }
            set { SetPropertyValue<DateTime>(nameof(CreatedDate), ref fCreatedDate, value); }
        }
        DateTime fRunOn;
        public DateTime RunOn
        {
            get { return fRunOn; }
            set { SetPropertyValue<DateTime>(nameof(RunOn), ref fRunOn, value); }
        }
        string fResult;
        [Size(SizeAttribute.Unlimited)]
        public string Result
        {
            get { return fResult; }
            set { SetPropertyValue<string>(nameof(Result), ref fResult, value); }
        }
    }

}
