//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Gripsrecylx.Module.BusinessObjects.Company1
{

    public partial class UserPrivilege : XPObject
    {
        User fUser;
        [Association(@"UserPrivilegeReferencesUser")]
        public User User
        {
            get { return fUser; }
            set { SetPropertyValue<User>(nameof(User), ref fUser, value); }
        }
        Privilege fPrivilege;
        [Association(@"UserPrivilegeReferencesPrivilege")]
        public Privilege Privilege
        {
            get { return fPrivilege; }
            set { SetPropertyValue<Privilege>(nameof(Privilege), ref fPrivilege, value); }
        }
    }

}
